/**
 * server/providers/anthropicBatch.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Anthropic Message Batches API — 50% cheaper than synchronous calls.
 *
 * WHY THIS FITS RESEARCH REPORTS
 * Reports are generated by a daily cron and cached for 24h. Nobody is waiting on
 * them, so trading latency for half the token cost is free money. Interactive
 * paths (explain, thesis, bulletin) stay synchronous — batch latency is measured
 * in minutes and would be visible there.
 *
 * DEGRADATION
 * Every failure mode here returns rather than throws past the caller's ability to
 * recover: if the batch cannot be submitted, or does not finish inside the poll
 * window, the caller falls back to synchronous generation. A slow report is worth
 * paying full price for; a missing report is not.
 * ─────────────────────────────────────────────────────────────────────────────
 */
"use strict";

const { fetchWithTimeout, withRetry, isRetryable } = require("../retry");
const { extractSearchSources } = require("./anthropic");

const BATCH_URL = "https://api.anthropic.com/v1/messages/batches";

// Batches usually land in minutes. 40 min is generous headroom for the daily job
// while still bounded — the cron runs at 09:37 and the cache holds for 24h.
const DEFAULT_POLL_INTERVAL_MS = 30_000;
const DEFAULT_POLL_TIMEOUT_MS  = 40 * 60_000;

function apiKey() {
  const k = process.env.ANTHROPIC_API_KEY;
  if (!k) throw new Error("ANTHROPIC_API_KEY not set — add it to .env");
  return k;
}

function headers() {
  return {
    "content-type":      "application/json",
    "x-api-key":         apiKey(),
    "anthropic-version": "2023-06-01",
  };
}

async function apiCall(url, options, timeoutMs = 60_000) {
  return withRetry(
    async () => {
      const res = await fetchWithTimeout(url, options, timeoutMs);
      if (!res.ok) {
        const errJson = await res.json().catch(() => ({}));
        const msg = errJson?.error?.message || `HTTP ${res.status}`;
        const err = new Error(`Anthropic Batch: ${msg}`);
        err.status = res.status;
        throw err;
      }
      return res.json();
    },
    {
      attempts: 3,
      baseMs:   4_000,
      maxMs:    20_000,
      shouldRetry: (e) => isRetryable(e) && e.name !== "AbortError" && e.status !== 401 && e.status !== 403,
    }
  );
}

/**
 * submitBatch — queue a set of Messages requests.
 *
 * @param {Array<{customId: string, system: string, prompt: string, maxTokens: number, model: string, tools?: Array}>} requests
 * @returns {Promise<string>} batch id
 */
async function submitBatch(requests) {
  if (!Array.isArray(requests) || requests.length === 0) {
    throw new Error("submitBatch: no requests supplied");
  }

  const body = {
    requests: requests.map(r => ({
      custom_id: r.customId,
      params: {
        model:      r.model,
        max_tokens: r.maxTokens,
        system:     r.system,
        messages:   [{ role: "user", content: r.prompt }],
        ...(r.tools ? { tools: r.tools } : {}),
      },
    })),
  };

  const json = await apiCall(BATCH_URL, {
    method:  "POST",
    headers: headers(),
    body:    JSON.stringify(body),
  });

  if (!json?.id) throw new Error("submitBatch: response carried no batch id");
  console.log(`[batch] submitted ${requests.length} request(s) — batch ${json.id}`);
  return json.id;
}

async function getBatchStatus(batchId) {
  return apiCall(`${BATCH_URL}/${batchId}`, { method: "GET", headers: headers() });
}

/**
 * fetchResults — pull the JSONL result stream and key it by custom_id.
 *
 * Results arrive in arbitrary order, so they must be keyed rather than indexed.
 * Each entry is `{ text, sources, error }`. `sources` carries the pages
 * web_search actually returned, so batched reports can resolve their cite
 * tags exactly as synchronously-generated ones do.
 */
async function fetchResults(resultsUrl) {
  const res = await fetchWithTimeout(resultsUrl, { headers: headers() }, 120_000);
  if (!res.ok) throw new Error(`Batch results: HTTP ${res.status}`);

  const raw = await res.text();
  const out = {};

  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    let entry;
    try { entry = JSON.parse(trimmed); }
    catch { console.warn("[batch] unparseable result line — skipped"); continue; }

    const id = entry.custom_id;
    if (!id) continue;

    if (entry.result?.type === "succeeded") {
      const content = entry.result.message?.content || [];
      const text = content
        .filter(b => b.type === "text")
        .map(b => b.text)
        .join("\n");
      // Keep the web_search_tool_result blocks. Filtering to text-only discarded
      // them, so every batched report finalised with an empty sources array and
      // its cite tags unresolvable — while still being marked grounded:true.
      // Same parser the synchronous path uses, so the two cannot drift.
      const sources = extractSearchSources(content);
      out[id] = { text, sources, error: null };
    } else {
      const reason = entry.result?.error?.message || entry.result?.type || "unknown";
      out[id] = { text: null, sources: [], error: reason };
      console.warn(`[batch] request ${id} did not succeed: ${reason}`);
    }
  }

  return out;
}

/**
 * pollBatch — wait for a batch to end, then return its results.
 * Resolves `null` on timeout so the caller can fall back to synchronous.
 */
async function pollBatch(batchId, {
  intervalMs = DEFAULT_POLL_INTERVAL_MS,
  timeoutMs  = DEFAULT_POLL_TIMEOUT_MS,
} = {}) {
  const deadline = Date.now() + timeoutMs;

  while (Date.now() < deadline) {
    const status = await getBatchStatus(batchId);

    if (status.processing_status === "ended") {
      if (!status.results_url) {
        console.warn(`[batch] ${batchId} ended with no results_url`);
        return null;
      }
      return fetchResults(status.results_url);
    }

    await new Promise(r => setTimeout(r, intervalMs));
  }

  console.warn(`[batch] ${batchId} did not end within ${Math.round(timeoutMs / 60_000)} min — caller should fall back`);
  return null;
}

/** runBatch — submit and wait. Returns null on any failure; never throws to the caller. */
async function runBatch(requests, opts = {}) {
  try {
    const batchId = await submitBatch(requests);
    return await pollBatch(batchId, opts);
  } catch (err) {
    console.warn("[batch] run failed — caller should fall back to synchronous:", err.message);
    return null;
  }
}

module.exports = { submitBatch, pollBatch, fetchResults, getBatchStatus, runBatch, BATCH_URL };
